# Generated by Django 2.1.1 on 2018-09-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
